# Generated by Django 3.1.7 on 2023-03-30 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
