# Generated by Django 3.1.7 on 2023-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projectapp', '0002_account_app_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
